package GorditoUwU.Bucles;

//Programa que muestre lo siguiente por pantalla:
//ZYWXVUTSRQPONMLKJIHGFEDCBA
//YWXVUTSRQPONMLKJIHGFEDCBA
//WXVUTSRQPONMLKJIHGFEDCBA
//XVUTSRQPONMLKJIHGFEDCBA
//VUTSRQPONMLKJIHGFEDCBA
//UTSRQPONMLKJIHGFEDCBA
//TSRQPONMLKJIHGFEDCBA
//SRQPONMLKJIHGFEDCBA
//RQPONMLKJIHGFEDCBA
//QPONMLKJIHGFEDCBA
//PONMLKJIHGFEDCBA
//ONMLKJIHGFEDCBA
//NMLKJIHGFEDCBA
//MLKJIHGFEDCBA
//LKJIHGFEDCBA
//KJIHGFEDCBA
//JIHGFEDCBA
//IHGFEDCBA
//HGFEDCBA
//GFEDCBA
//FEDCBA
//EDCBA
//DCBA
//CBA
//BA
//A

public class ejercicio34 {
}
